language: node_js
node_js:
  - 12

jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: audit
      script:
        - npm run audit
    - stage: test
      script:
        - npm test
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
